### ISSUE TITLE
Discussion on only using yaml options that are independent of apaquarto

### ISSUE THREAD

**Issue by FlorianPargent** [lmu-osc/code-publishing#1]
I just checked the Quarto documentation and I think the relevant site for manuscript options that are independent on specific journal formats is the section on *“Scholarly Writing”* that start on this page:

https://quarto.org/docs/authoring/front-matter.html

As far as I can see, this includes all the options we need:
Author names, affiliation, email, orcid ids, contributor roles, corresponding author, abstract, key words, etc.

I think the only option in your minimal penguin example at the moment that is apaquarto specific would be `floatsintext: true`

**Comment by fkohrt** [comment]
Good idea, I removed `floatsintext` via 8e4da23
