### ISSUE TITLE
More prominent links to the other tutorials

### ISSUE THREAD

**Issue by FlorianPargent** [lmu-osc/code-publishing#12]
I think I would prefer, if the links to our other tutorials are more prominent so that readers can see more clearly how this tutorial is something like the final step of all the things they have learned previously. I see at least two options how this could be achieved:

- Include a full list with links to all our other tutorials you rely upon (and a short sentence on what they contain) on the *Introduction* page
- Chose a certain type of callout box you do not use otherwise and always place the link to another tutorial in such a box whenever it is relevant throught your tutorial. For example, on your *Project setup* page, the sentence "If you don’t know what Git is, have a look at the tutorial *Introduction to version control with git and GitHub within RStudio*." could be placed in such a callout box.

**Comment by fkohrt** [comment]
I went for the first way via c132272
