### ISSUE TITLE
Comment on license section

### ISSUE THREAD

**Issue by FlorianPargent** [lmu-osc/code-publishing#13]
I have just read the license section and learned a lot! Unfortunately, I think it is quite intimidating and I fear it is still not clear for the average reader with the average project what to do (it also is not fully clear to myself, as I have not spent enough time thinking about licenses myself). I try to list some of my thoughts:

- For our intended readership, I assume an average project contains 1) some data the author is allowed to use (because it is their own or published under an appropriate license) or links to a data repository in the documentation if the data cannot be shared, 2) some scripting code to analyse data using open source software like R and its packages, 3) some literate programming code like Quarto code, 4) some outputs like PDFs of a manuscript or figures, 5) some metadata like README files for the project.
- I am not sure the average reader (including me) knows how to license the project after reading the tutorial. Some things which might still be unclear (or could be made more clear) might be:
    - When you talk about "Software" in the tutorial, does this include 1) every piece of R code I wrote to analyse my data, 2) every piece of Quarto etc. code I wrote in order to make my writing reproducible?
    - Is there a difference between some code I wrote that I can expect to really be useful to others (e.g. I wrote a new function for some specific analysis step that others might use exactly like I wrote it), and code that I wrote to perform my analysis and produce my reproducible manuscript but I would not expect to be useful to others?
    - Assume that I as the average author want to publish a research compendium which is something like reproducible supplementary files to my research article that will hopefully soon be published in a journal. 1) I want to include a permissive license to signal others that they can do with my project whatever they want. In theory, I do not need an attribution license because scientific norms require my colleagues to cite me anyways if they used my materials in their own research (although most researchers might still want attribution to be included in the license). 2) I want to make sure that I do not accidentally license anything under a license I am not allowed to. I expect that readers of my work assume good faith on my part with respect to this point because I am a researcher and not a software engineer and I have not developed "anything" new except from the analyses and interpretation of results I have outlined in my research manuscript. Can you give some advice on shortcutting your flowcharts in this case (I suppose not, but maybe there is). I admit that in my own projects, I have in the past always just added a CC-BY license to my project without further explanation, although I know that this is not really how this licensing stuff works but I always hoped that at least no real harm will come from that?
- Could you include in the wrap-up of the licensing section something that prevents readers to be too frightened by the license choice? Readers' fear to make mistakes in licensing should not prevent them from publishing reproducible materials for their research!

**Comment by fkohrt** [comment]
This is a very good point. I added a TL;DR via 3f2f2e8.

I will leave this issue open because (1) I am interested whether this adequately addresses your second bullet point, and (2) your third still needs to be addressed.

**Comment by fkohrt** [comment]
Regarding (2), I added the following statement to the TL;DR via 45c8a91:

> Except where noted otherwise, all files in this project are made available under CC0 1.0 or (at your option) under the terms of the Apache Software License 2.0.

@FlorianPargent do you think all your points are now addressed?

**Comment by fkohrt** [comment]
If I find the time, I will add a note about using work by others (see #22). Apart from that, I think this issue can be closed.
