### ISSUE TITLE
Github bug License of the code-publishing project

### ISSUE THREAD

**Issue by FlorianPargent** [lmu-osc/code-publishing#14]
It seems that there is some weird unintended behavior with Github and the license of this project. When I go to the main project page (https://github.com/lmu-osc/code-publishing) there is the README tab and next to it the LICENSE tab, where Github currently displays the content of the `choose_license.qmd` file... Perhaps rename that file so that Github does not think that it contains the license of the project?

**Comment by fkohrt** [comment]
Interesting! Fixed via d1a0bb6
