### ISSUE TITLE
apa7.cls vs. apa7.csl

### ISSUE THREAD

**Issue by FlorianPargent** [lmu-osc/code-publishing#3]
For some reason the project contains both a apa7.cls and a apa7.csl file.
Could it be that you added one of these files manually and the other was added automatically by apaquarto?
Right now I am very confused what is the common file abbreviation.
Googling seems to suggest that both .cls and .csl exist in the wild...

**Comment by fkohrt** [comment]
I think that both are superfluous and removed them in 973868d
