### ISSUE TITLE
Refer to Zotero tutorial?

### ISSUE THREAD

**Issue by NeuroShepherd** [lmu-osc/code-publishing#8]
@fkohrt do you intend to have the summer school students read through the Zotero tutorial prior to reading the content from this code publishing tutorial? 

The Zotero tutorial is still in progress, but I can make sure a readable, useful version of it is available in advance of the code publishing tutorial session next Friday.

**Comment by MalikaIhle** [comment]
they wont read the renv nor the zotero but they will have access to it when interested during the code publishing tutorial.

**Comment by fkohrt** [comment]
Thanks @NeuroShepherd, I am happy to link to the Zotero tutorial! I will also take a look at it and see whether some of the practices taught in your tutorial can also be applied by the participants of the code publishing tutorial. However, I already fear that the two hours won't suffice to work through the material, so I'll see about hat :)

**Comment by fkohrt** [comment]
I provide a link to the Zotero tutorial in the beginning, see also #12
